from django.conf.urls import  url
from .views import (
    TrainerCreateView,
    TrainerDeleteView,
    TrainerDetailView,
    TrainerUpdateView,
    TrainerListView,
    trainer_enable,
    trainer_disable,
    ClientDeleteView,
    ClientDetailView,
    ClientNoteUpdateView,
    ClientChangeTrainerUpdateView,
    ClientListView,
    client_enable,
    client_disable,
    FoodProgramCloneCreateView,
    FoodProgramCreateView,
    FoodProgramDetailView,
    FoodProgramUpdateView,
    FoodProgramDeleteView,
    food_create,
    food_delete,
    WorkoutCreateView,
    WorkoutCloneCreateView,
    WorkoutDetailView,
    WorkoutUpdateView,
    WorkoutDeleteView,
    training_create,
    training_delete,
    WsetCreateView,
    LeadUserListView,
    # LeadUserCreateView,
    LeadUserDetailView,
    leaduser_enable,
    leaduser_disable,
    CountersUpdateView,
    WsetUpdateView,
    )

urlpatterns = [
    url(r'^trainers/$', TrainerListView.as_view(), name="trainer_list"),
    url(r'^trainers/add/$', TrainerCreateView.as_view(), name="trainer_create"),
    url(r'^trainers/(?P<pk>\d+)/update/$', TrainerUpdateView.as_view(), name='trainer_update'),
    url(r'^trainers/(?P<pk>\d+)/detail/$', TrainerDetailView.as_view(), name='trainer_detail'),
    url(r'^trainers/(?P<pk>\d+)/delete/$', TrainerDeleteView.as_view(), name='trainer_delete'),
    url(r'^trainers/(?P<pk>\d+)/enable/$', trainer_enable, name='trainer_enable'),
    url(r'^trainers/(?P<pk>\d+)/disable/$', trainer_disable, name='trainer_disable'),
    url(r'^clients/$', ClientListView.as_view(), name="client_list"),
    url(r'^clients/(?P<slug>[\w.@+-]+)/noteupdate/$', ClientNoteUpdateView.as_view(), name='client_note_update'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/counters/$', CountersUpdateView.as_view(), name='counters_update'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/change-trainer/$', ClientChangeTrainerUpdateView.as_view(), name='client_change_trainer'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/detail/$', ClientDetailView.as_view(), name='client_detail'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/delete/$', ClientDeleteView.as_view(), name='client_delete'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/enable/$', client_enable, name='client_enable'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/disable/$', client_disable, name='client_disable'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/foodprogram/add/$', FoodProgramCreateView.as_view(), name="foodprogram_create"),
    url(r'^clients/(?P<slug>[\w.@+-]+)/foodprogram/(?P<pk>\d+)/clone/$', FoodProgramCloneCreateView.as_view(), name='foodprogramclone_create'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/foodprogram/(?P<pk>\d+)/update/$', FoodProgramUpdateView.as_view(), name='foodprogram_update'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/foodprogram/(?P<pk>\d+)/detail/$', FoodProgramDetailView.as_view(), name='foodprogram_detail'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/foodprogram/(?P<pk>\d+)/delete/$', FoodProgramDeleteView.as_view(), name='foodprogram_delete'),
    url(r'^clients/foodprogram/food/add/$', food_create, name='food_create'),
    url(r'^clients/foodprogram/food/delete/$', food_delete, name='food_delete'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/workout/add/$', WorkoutCreateView.as_view(), name="workout_create"),
    url(r'^clients/(?P<slug>[\w.@+-]+)/workout/(?P<pk>\d+)/clone/$', WorkoutCloneCreateView.as_view(), name='workoutclone_create'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/workout/(?P<pk>\d+)/update/$', WorkoutUpdateView.as_view(), name='workout_update'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/workout/(?P<pk>\d+)/detail/$', WorkoutDetailView.as_view(), name='workout_detail'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/workout/(?P<pk>\d+)/delete/$', WorkoutDeleteView.as_view(), name='workout_delete'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/workout/(?P<pk>\d+)/sets/add/$', WsetCreateView.as_view(), name='wset_create'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/workout/(?P<sk>\d+)/sets/(?P<pk>\d+)/update/$', WsetUpdateView.as_view(), name='wset_update'),
    url(r'^clients/workout/sets/training/add/$', training_create, name='training_create'),
    url(r'^clients/workout/sets/training/delete/$', training_delete, name='training_delete'),
    url(r'^leadusers/$', LeadUserListView.as_view(), name='leaduser_list'),
    url(r'^leadusers/(?P<pk>\d+)/(?P<chatid>[\w-]+)/$', LeadUserDetailView.as_view(), name='leaduser_detail'),
    url(r'^leadusers/(?P<pk>\d+)/(?P<chatid>[\w-]+)/enable/$', leaduser_enable, name='leaduser_enable'),
    url(r'^leadusers/(?P<pk>\d+)/(?P<chatid>[\w-]+)/disable/$', leaduser_disable, name='leaduser_disable'),

]








