from django.conf.urls import  url
from accounts.api.views import (
    BossTrainerRetrieveAPIView,
    ClientCreateAPIView,
    ClientFoodProgramUpdateAPIView,
    ClientMessagesAPIView,
    ClientMessageStatusUpdateAPIView,
    ClientProgressRetrieveAPIView,
    ClientRetrieveAPIView,
    ClientShortRetrieveAPIView,
    ExerciseCommentCreateAPIView,
    ExerciseCommentRetrieveAPIView,
    FavouriteCreateAPIView,
    FavouriteDeleteAPIView,
    FoodProgramRetrieveAPIView,
    LeadUserCreateAPIView,
    LeadUserMessagesAPIView,
    LeadUserMessageStatusUpdateAPIView,
    LeadUserRetrieveAPIView,
    MarafonProgramListAPIView,
    PersonalNutrimentProfileRetrieveAPIView,
    PersonalWorkoutProfileRetrieveAPIView,
    ProgramByCategoryListAPIView,
    ProgramCategoryListAPIView,
    ProgramListAPIView,
    ProgramRetrieveAPIView,
    ProgressCreateAPIView,
    ProgressRetrieveAPIView,
    RegenerateFood,
    WorkoutCommentCreateAPIView,
    WorkoutRetrieveAPIView,
    )


urlpatterns = [
    url(r'^clients/add$', ClientCreateAPIView.as_view(), name='client_create_api'),
    url(r'^leadusers/add/$', LeadUserCreateAPIView.as_view(), name='leaduser_create_api'),
    url(r'^leadusers/(?P<pk>\d+)/$', LeadUserRetrieveAPIView.as_view(), name='leaduser_detail_api'),
    url(r'^leadusers/(?P<pk>\d+)/messages/$', LeadUserMessagesAPIView.as_view(), name='leaduser_message_status_update'),
    url(r'^leadusers/(?P<pk>\d+)/messages/status/$', LeadUserMessageStatusUpdateAPIView.as_view(), name='message_status_update_api'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/detail/$', ClientRetrieveAPIView.as_view(), name='client_detail_api'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/regenerate-food/$', RegenerateFood.as_view(), name='client_regenerate_api'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/detail-short/$', ClientShortRetrieveAPIView.as_view(), name='client_short_detail_api'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/progress/$', ClientProgressRetrieveAPIView.as_view(), name='client_progress_detail_api'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/messages/$', ClientMessagesAPIView.as_view(), name='client_messages_api'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/messages/status/$', ClientMessageStatusUpdateAPIView.as_view(), name='client_message_status_update'),
    url(r'^clients/(?P<slug>[\w.@+-]+)/foodprograms-update/$', ClientFoodProgramUpdateAPIView.as_view(), name='client_foodprograms_update'),
    url(r'^clients/personal-workout-profile/(?P<pk>\d+)/detail/$', PersonalWorkoutProfileRetrieveAPIView.as_view(), name='personal_workout_profile'),
    url(r'^clients/personal-nutriment-profile/(?P<pk>\d+)/detail/$', PersonalNutrimentProfileRetrieveAPIView.as_view(), name='personal_nutriment_profile'),
    url(r'^trainers/bosstrainer/$', BossTrainerRetrieveAPIView.as_view(), name='bosstrainer_detail_api'),
    url(r'^progress/create/$', ProgressCreateAPIView.as_view(), name='progress_create_api'),
    url(r'^progress/(?P<pk>\d+)/$', ProgressRetrieveAPIView.as_view(), name='progress_create_api'),
    url(r'^workouts/(?P<pk>\d+)/$', WorkoutRetrieveAPIView.as_view(), name='workout_detail_api'),
    url(r'^marafon-programs/$', MarafonProgramListAPIView.as_view(), name='marafon_programs_list_api'),
    url(r'^favourite/add$', FavouriteCreateAPIView.as_view(), name='favourite_create_api'),
    url(r'^favourite/(?P<pk>\d+)/delete$', FavouriteDeleteAPIView.as_view(), name='favourite_delete_api'),
    url(r'^clients/foodprograms/(?P<pk>\d+)/$', FoodProgramRetrieveAPIView.as_view(), name='foodprogram_detail_api'),
    url(r'^workouts/comments/create/$', WorkoutCommentCreateAPIView.as_view(), name='workoutcomment_create_api'),
    url(r'^workouts/comments/exercise/create/$', ExerciseCommentCreateAPIView.as_view(), name='exercisecomment_create_api'),
    url(r'^workouts/comments/exercise/(?P<pk>\d+)/$', ExerciseCommentRetrieveAPIView.as_view(), name='exercisecomment_detail_api'),
    url(r'^programs/categories/$', ProgramCategoryListAPIView.as_view(), name='program_category_list_api'),
    url(r'^programs/categories/(?P<pk>\d+)/$', ProgramByCategoryListAPIView.as_view(), name='program_by_category_list_api'),
    url(r'^programs/$', ProgramListAPIView.as_view(), name='program_list_api'),
    url(r'^programs/(?P<pk>\d+)/$', ProgramRetrieveAPIView.as_view(), name='program_detail_api'),
]